services:
  tests-unit:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: library-tests-unit
    command: ["LibrarySystem.UnitTests/LibrarySystem.UnitTests.csproj", "--logger:trx"]
    volumes:
      - ./TestResults:/src/LibrarySystem.UnitTests/TestResults

  tests-integration:
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: library-tests-integration
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
    command: ["LibrarySystem.IntegrationTests/LibrarySystem.IntegrationTests.csproj", "--logger:trx"]
    volumes:
      - ./TestResults:/src/LibrarySystem.IntegrationTests/TestResults