FROM ubuntu:24.04
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY services/cpp-compute/build/cpp_compute .

EXPOSE 50052
ENTRYPOINT ["./cpp_compute"]
